### PR TITLE
docs: rephrases already existing documentation

### PR DESCRIPTION
**Pull request by paschalidi**
Hey @amcgee 👋 

This is what I meant with my issue here: https://github.com/dhis2/app-platform/issues/353

Have a look and feel more than free to close the issue if it doesn't make sense to you :)

### CODE REVIEW

**Comment by amcgee** [comment]
Hey @paschalidi, thanks for the suggestion!  For me this is not as clear as the original, but I may have some bias - @dhis2/team-apps anyone have an opinion here?  (low-priority)

**Comment by paschalidi** [comment]
As you said is simply a suggestion.

**Comment by Mohammer5** [comment]
I'm in favor of keeping the current version as it highlights the distinction between manual and automated installation of the dev dependency while the change tries to highlight a distinction between a globally and locally available package, which should be an addition the the former instead of replacing it if we think we need this distinction.

**Comment by amcgee** [comment]
Thanks @Mohammer5, well-put!  @paschalidi do you want to update this so that it adds a new sentence about "global" installation and usage?

**Comment by amcgee** [comment]
Actually the preceding paragraph does this already:

> To run the `init` script as a stand-alone tool, either install the D2 cli globally (`yarn global add @dhis2/cli`) and run `d2 app scripts init myapp`, or run the `init` script by itself with `npx` (`npx @dhis2/cli-app-scripts init myapp`)

Feel free to suggest a clarification there if needed, otherwise I think we can close this PR?

**Comment by paschalidi** [comment]
Yes we can close the PR indeed. Thanks both for looking into it!!

**Pull request closed without merging**
