### PR TITLE
revert: keep default values that may have been set (#382)

### PR DESCRIPTION
**Pull request by jenniferarnesen**
This reverts commit 4b6e275969713014a9958cef0be256a00f16ef9a.

Upload to transifex fails when there are translations in the pot file, which is what this commit introduced. We'll have to solve translations for plurals in a different way.

### CODE REVIEW

**Comment by amcgee** [comment]
Should we instead generate an `en.po` file?  Would that work with Transifex if `en.pot` also exists?

**Comment by jenniferarnesen** [comment]
> Should we instead generate an `en.po` file? Would that work with Transifex if `en.pot` also exists?

@amcgee I added a comment to this issue explaining what I've found. https://github.com/dhis2/app-platform/issues/369#issuecomment-704839627 Would very much appreciate input.

**Comment by jenniferarnesen** [comment]
> Should we instead generate an `en.po` file? Would that work with Transifex if `en.pot` also exists?

Good suggestion. We would probably want to get rid of the pot file then.

**Comment by amcgee** [comment]
> Good suggestion. We would probably want to get rid of the pot file then.

Don't we need this for Transifex?

**Review by amcgee — APPROVED** [review]
LGTM, though we'll want to figure out a better solution...

**Pull request closed without merging**
